API:
  HOST: http://127.0.0.1:8000
  PATH: /api
  OAUTH:
    PATH: /oauth


###########################################
#    External OAuth services parameters   #
###########################################
oauth:
  callback: /oauth/callback
  providers:
    google:
      scopes: 
      - https://www.googleapis.com/auth/userinfo.email
      - openid
      urls:
        code: https://accounts.google.com/o/oauth2/v2/auth
        token: https://oauth2.googleapis.com/token
        public_keys: https://www.googleapis.com/oauth2/v3/certs


#############################################
#                LOGGING                    #
#############################################
ERROR_LOG_FILENAME: "oauth_client_lib.log"
