"""token: scope, token_type, id_token added

Revision ID: 050dfdc2a1f0
Revises: 299da1c195c8
Create Date: 2023-02-08 18:34:54.420446

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '050dfdc2a1f0'
down_revision = '299da1c195c8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
