"""account: hashed_password added

Revision ID: 299da1c195c8
Revises: 46ec36f16716
Create Date: 2022-12-01 08:33:22.439763

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '299da1c195c8'
down_revision = '46ec36f16716'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('hashed_password', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accounts', 'hashed_password')
    # ### end Alembic commands ###
