"""email - check_code added

Revision ID: 46ec36f16716
Revises: b3bffa9af75d
Create Date: 2022-11-30 17:31:47.255885

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46ec36f16716'
down_revision = 'b3bffa9af75d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('emails', sa.Column('check_code', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('emails', 'check_code')
    # ### end Alembic commands ###
