"""token: scope, token_type, id_token added into model

Revision ID: aa81d3a72a8b
Revises: 050dfdc2a1f0
Create Date: 2023-02-08 18:42:12.889365

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa81d3a72a8b'
down_revision = '050dfdc2a1f0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tokens', sa.Column('token_type', sa.String(), nullable=True))
    op.add_column('tokens', sa.Column('scope', sa.String(), nullable=True))
    op.add_column('tokens', sa.Column('id_token', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tokens', 'token_type')
    op.drop_column('tokens', 'scope')    
    op.drop_column('tokens', 'id_token')    
    # ### end Alembic commands ###
